# Generated by Django 6.0.5 on 2026-06-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Місячний ліміт (грн)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Опис транзакції')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (грн)')),
                ('type', models.CharField(choices=[('debit', 'Дебет (Дохід)'), ('credit', 'Кредит (Витрата)')], max_length=10, verbose_name='Тип транзакції')),
                ('date', models.DateField(verbose_name='Дата транзакції')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions_app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
